platform: linux
image_resource:
  type: docker-image
  source:
    repository: dpb587/bosh-compiled-releases
    tag: master-main
inputs:
  - name: repo
  - name: release
outputs:
  - name: repo
    path: repo-output
run:
  path: repo/concourse/tasks/import-metalinks/execute.sh
params:
  repository: ~
  release_dir: ../release
  git_user_email: concourse.ci@localhost
  git_user_name: Concourse
