platform: linux
image_resource:
  type: docker-image
  source:
    repository: dpb587/bosh-compiled-releases
    tag: master-main
inputs:
  - name: repo
  - name: cf-deployment
outputs:
  - name: repo
    path: repo-output
run:
  path: repo/concourse/tasks/import-cf-deployment/execute.sh
params:
  git_user_email: concourse.ci@localhost
  git_user_name: Concourse
