platform: linux
image_resource:
  type: docker-image
  source:
    repository: dpb587/bosh-compiled-releases
    tag: master-main
inputs:
  - name: repo
    path: gopath/github.com/dpb587/bosh-compiled-releases
outputs:
  - name: app
run:
  path: gopath/src/github.com/dpb587/bosh-compiled-releases/concourse/tasks/build-app/execute.sh
