#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$DIR/.."

GOOS=darwin GOARCH=amd64 go build -o "$DIR/bcr-darwin-amd64" cli/main.go
GOOS=linux GOARCH=amd64 go build -o "$DIR/bcr-linux-amd64" cli/main.go

find data -name bcr.json | xargs cat > "$DIR/bcr.json"
