#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$DIR/.."

GOOS=linux GOARCH=amd64 go build -o "$DIR/cli" cli/main.go

find data -name bcr.json | xargs cat > "$DIR/bcr.json"

cd "$DIR"

exec cf push -b https://github.com/cloudfoundry/binary-buildpack.git -c './cli serve --local=bcr.json' -i 1 -m 64M -k 32M "$@"
