{
  "jobs": [
    {
      "name": "github-dpb587-openvpn-bosh-release-ubuntu-trusty",
      "serial_groups": [
        "pipeline"
      ],
      "plan": [
        {
          "aggregate": [
            {
              "get": "release",
              "resource": "github-dpb587-openvpn-bosh-release",
              "trigger": true
            },
            {
              "get": "stemcell"
              resource: "ubuntu-trusty"
              trigger: true
            }
          ]
        },
        {
          "get": "release-compiler"
        },
        {
          "task": "compile-release",
          "file": "release-compiler/concourse/execute-local-bosh.yml",
          "privileged": true
        },
        {
          "get": "repo"
        },
        {
          "task": "finalize-compiled-release",
          "file": "repo/ci/tasks/finalize-compiled-release/task.yml",
          "params": {
            "repository": "github.com/dpb587/openvpn-bosh-release",
            "s3_host": "((s3_host))",
            "s3_bucket": "((s3_bucket))",
            "s3_access_key": "((s3_access_key))",
            "s3_secret_key": "((s3_secret_key))",
            "git_commit_message": "openvpn: add compiled release",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "task": "import-metalinks",
          "file": "repo/ci/tasks/finalize-compiled-release/task.yml",
          "params": {
            "repository": "github.com/dpb587/openvpn-bosh-release",
            "git_commit_message": "openvpn: update compiled releases",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "put": "repo",
          "params": {
            "rebase": true,
            "repository": "repo"
          }
        }
      ]
    }
  ],
  "resources": [
    {
      "name": "release-compiler",
      "type": "git",
      "source": {
        "uri": "https://github.com/dpb587/bosh-release-compiler.git"
      }
    },
    {
      "name": "repo",
      "type": "git",
      "source": {
        "branch": "master",
        "private_key": "((git_private_key))",
        "uri": "git@github.com:dpb587/bosh-compiled-release.git"
      }
    },
    {
      "name": "ubuntu-trusty",
      "type": "metalink-repository",
      "source": {
        "uri": "https://dpb587.github.io/upstream-blob-mirror/repository/bosh.io/stemcell/bosh-warden-boshlite-ubuntu-trusty-go_agent/index.xml"
      }
    },
    {
      "name": "github-dpb587-openvpn-bosh-release",
      "type": "metalink-repository",
      "source": {
        "uri": "https://dpb587.github.io/upstream-blob-mirror/repository/bosh.io/stemcell/bosh-warden-boshlite-ubuntu-trusty-go_agent/index.xml"
      }
    }
  ],
  "resource_types": [
    {
      "name": "metalink-repository",
      "type": "docker-image",
      "source": {
        "repository": "dpb587/metalink-repository-resource"
      }
    }
  ]
}
