{
  "jobs": [
    {
      "name": "bosh-io-cloudfoundry-bosh-ubuntu-trusty",
      "serial_groups": [
        "compiler"
      ],
      "plan": [
        {
          "aggregate": [
            {
              "get": "release",
              "resource": "bosh-io-cloudfoundry-bosh",
              "trigger": true
            },
            {
              "get": "stemcell",
              resource: "ubuntu-trusty",
              trigger: true
            }
          ]
        },
        {
          "get": "release-compiler"
        },
        {
          "task": "compile-release",
          "file": "release-compiler/concourse/execute-local-bosh.yml",
          "privileged": true
        },
        {
          "get": "repo"
        },
        {
          "task": "finalize-compiled-release",
          "file": "repo/concourse/tasks/finalize-compiled-release/config.yml",
          "params": {
            "repository": "github.com/cloudfoundry/bosh",
            "s3_host": "((s3_host))",
            "s3_bucket": "((s3_bucket))",
            "s3_access_key": "((s3_access_key))",
            "s3_secret_key": "((s3_secret_key))",
            "git_commit_message": "bosh: add compiled release",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "task": "import-metalinks",
          "file": "repo/concourse/tasks/import-metalinks/config.yml",
          "params": {
            "repository": "github.com/cloudfoundry/bosh",
            "git_commit_message": "bosh: update bcr.json",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "put": "repo",
          "params": {
            "rebase": true,
            "repository": "repo"
          }
        }
      ]
    },
    {
      "name": "bosh-io-concourse-concourse-ubuntu-trusty",
      "serial_groups": [
        "compiler"
      ],
      "plan": [
        {
          "aggregate": [
            {
              "get": "release",
              "resource": "bosh-io-concourse-concourse",
              "trigger": true
            },
            {
              "get": "stemcell",
              resource: "ubuntu-trusty",
              trigger: true
            }
          ]
        },
        {
          "get": "release-compiler"
        },
        {
          "task": "compile-release",
          "file": "release-compiler/concourse/execute-local-bosh.yml",
          "privileged": true
        },
        {
          "get": "repo"
        },
        {
          "task": "finalize-compiled-release",
          "file": "repo/concourse/tasks/finalize-compiled-release/config.yml",
          "params": {
            "repository": "github.com/concourse/concourse",
            "s3_host": "((s3_host))",
            "s3_bucket": "((s3_bucket))",
            "s3_access_key": "((s3_access_key))",
            "s3_secret_key": "((s3_secret_key))",
            "git_commit_message": "concourse: add compiled release",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "task": "import-metalinks",
          "file": "repo/concourse/tasks/import-metalinks/config.yml",
          "params": {
            "repository": "github.com/concourse/concourse",
            "git_commit_message": "concourse: update bcr.json",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "put": "repo",
          "params": {
            "rebase": true,
            "repository": "repo"
          }
        }
      ]
    },
    {
      "name": "bosh-io-cloudfoundry-garden-runc-release-ubuntu-trusty",
      "serial_groups": [
        "compiler"
      ],
      "plan": [
        {
          "aggregate": [
            {
              "get": "release",
              "resource": "bosh-io-cloudfoundry-garden-runc-release",
              "trigger": true
            },
            {
              "get": "stemcell",
              resource: "ubuntu-trusty",
              trigger: true
            }
          ]
        },
        {
          "get": "release-compiler"
        },
        {
          "task": "compile-release",
          "file": "release-compiler/concourse/execute-local-bosh.yml",
          "privileged": true
        },
        {
          "get": "repo"
        },
        {
          "task": "finalize-compiled-release",
          "file": "repo/concourse/tasks/finalize-compiled-release/config.yml",
          "params": {
            "repository": "github.com/cloudfoundry/garden-runc-release",
            "s3_host": "((s3_host))",
            "s3_bucket": "((s3_bucket))",
            "s3_access_key": "((s3_access_key))",
            "s3_secret_key": "((s3_secret_key))",
            "git_commit_message": "garden-runc: add compiled release",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "task": "import-metalinks",
          "file": "repo/concourse/tasks/import-metalinks/config.yml",
          "params": {
            "repository": "github.com/cloudfoundry/garden-runc-release",
            "git_commit_message": "garden-runc: update bcr.json",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "put": "repo",
          "params": {
            "rebase": true,
            "repository": "repo"
          }
        }
      ]
    },
    {
      "name": "bosh-io-cloudfoundry-uaa-release-ubuntu-trusty",
      "serial_groups": [
        "compiler"
      ],
      "plan": [
        {
          "aggregate": [
            {
              "get": "release",
              "resource": "bosh-io-cloudfoundry-uaa-release",
              "trigger": true
            },
            {
              "get": "stemcell",
              resource: "ubuntu-trusty",
              trigger: true
            }
          ]
        },
        {
          "get": "release-compiler"
        },
        {
          "task": "compile-release",
          "file": "release-compiler/concourse/execute-local-bosh.yml",
          "privileged": true
        },
        {
          "get": "repo"
        },
        {
          "task": "finalize-compiled-release",
          "file": "repo/concourse/tasks/finalize-compiled-release/config.yml",
          "params": {
            "repository": "github.com/cloudfoundry/uaa-release",
            "s3_host": "((s3_host))",
            "s3_bucket": "((s3_bucket))",
            "s3_access_key": "((s3_access_key))",
            "s3_secret_key": "((s3_secret_key))",
            "git_commit_message": "uaa: add compiled release",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "task": "import-metalinks",
          "file": "repo/concourse/tasks/import-metalinks/config.yml",
          "params": {
            "repository": "github.com/cloudfoundry/uaa-release",
            "git_commit_message": "uaa: update bcr.json",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "put": "repo",
          "params": {
            "rebase": true,
            "repository": "repo"
          }
        }
      ]
    },
    {
      "name": "bosh-io-cloudfoundry-community-docker-registry-boshrelease-ubuntu-trusty",
      "serial_groups": [
        "compiler"
      ],
      "plan": [
        {
          "aggregate": [
            {
              "get": "release",
              "resource": "bosh-io-cloudfoundry-community-docker-registry-boshrelease",
              "trigger": true
            },
            {
              "get": "stemcell",
              resource: "ubuntu-trusty",
              trigger: true
            }
          ]
        },
        {
          "get": "release-compiler"
        },
        {
          "task": "compile-release",
          "file": "release-compiler/concourse/execute-local-bosh.yml",
          "privileged": true
        },
        {
          "get": "repo"
        },
        {
          "task": "finalize-compiled-release",
          "file": "repo/concourse/tasks/finalize-compiled-release/config.yml",
          "params": {
            "repository": "github.com/cloudfoundry-community/docker-registry-boshrelease",
            "s3_host": "((s3_host))",
            "s3_bucket": "((s3_bucket))",
            "s3_access_key": "((s3_access_key))",
            "s3_secret_key": "((s3_secret_key))",
            "git_commit_message": "docker-registry: add compiled release",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "task": "import-metalinks",
          "file": "repo/concourse/tasks/import-metalinks/config.yml",
          "params": {
            "repository": "github.com/cloudfoundry-community/docker-registry-boshrelease",
            "git_commit_message": "docker-registry: update bcr.json",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "put": "repo",
          "params": {
            "rebase": true,
            "repository": "repo"
          }
        }
      ]
    },
    {
      "name": "bosh-io-cloudfoundry-syslog-release-ubuntu-trusty",
      "serial_groups": [
        "compiler"
      ],
      "plan": [
        {
          "aggregate": [
            {
              "get": "release",
              "resource": "bosh-io-cloudfoundry-syslog-release",
              "trigger": true
            },
            {
              "get": "stemcell",
              resource: "ubuntu-trusty",
              trigger: true
            }
          ]
        },
        {
          "get": "release-compiler"
        },
        {
          "task": "compile-release",
          "file": "release-compiler/concourse/execute-local-bosh.yml",
          "privileged": true
        },
        {
          "get": "repo"
        },
        {
          "task": "finalize-compiled-release",
          "file": "repo/concourse/tasks/finalize-compiled-release/config.yml",
          "params": {
            "repository": "github.com/cloudfoundry/syslog-release",
            "s3_host": "((s3_host))",
            "s3_bucket": "((s3_bucket))",
            "s3_access_key": "((s3_access_key))",
            "s3_secret_key": "((s3_secret_key))",
            "git_commit_message": "syslog: add compiled release",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "task": "import-metalinks",
          "file": "repo/concourse/tasks/import-metalinks/config.yml",
          "params": {
            "repository": "github.com/cloudfoundry/syslog-release",
            "git_commit_message": "syslog: update bcr.json",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "put": "repo",
          "params": {
            "rebase": true,
            "repository": "repo"
          }
        }
      ]
    },
    {
      "name": "bosh-io-cloudfoundry-dns-release-ubuntu-trusty",
      "serial_groups": [
        "compiler"
      ],
      "plan": [
        {
          "aggregate": [
            {
              "get": "release",
              "resource": "bosh-io-cloudfoundry-dns-release",
              "trigger": true
            },
            {
              "get": "stemcell",
              resource: "ubuntu-trusty",
              trigger: true
            }
          ]
        },
        {
          "get": "release-compiler"
        },
        {
          "task": "compile-release",
          "file": "release-compiler/concourse/execute-local-bosh.yml",
          "privileged": true
        },
        {
          "get": "repo"
        },
        {
          "task": "finalize-compiled-release",
          "file": "repo/concourse/tasks/finalize-compiled-release/config.yml",
          "params": {
            "repository": "github.com/cloudfoundry/dns-release",
            "s3_host": "((s3_host))",
            "s3_bucket": "((s3_bucket))",
            "s3_access_key": "((s3_access_key))",
            "s3_secret_key": "((s3_secret_key))",
            "git_commit_message": "dns: add compiled release",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "task": "import-metalinks",
          "file": "repo/concourse/tasks/import-metalinks/config.yml",
          "params": {
            "repository": "github.com/cloudfoundry/dns-release",
            "git_commit_message": "dns: update bcr.json",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "put": "repo",
          "params": {
            "rebase": true,
            "repository": "repo"
          }
        }
      ]
    },
    {
      "name": "github-dpb587-openvpn-bosh-release",
      "plan": [
        {
          "get": "release",
          "resource": "github-dpb587-openvpn-bosh-release",
          "trigger": true
        },
        {
          "get": "repo"
        },
        {
          "task": "import-metalinks",
          "file": "repo/concourse/tasks/import-metalinks/config-release.yml",
          "params": {
            "repository": "github.com/dpb587/openvpn-bosh-release",
            "git_commit_message": "openvpn: update bcr.json",
            "git_user_email": "((maintainer_email))",
            "git_user_name": "((maintainer_name))"
          }
        },
        {
          "put": "repo",
          "params": {
            "rebase": true,
            "repository": "repo"
          }
        }
      ]
    }
  ],
  "resources": [
    {
      "name": "release-compiler",
      "type": "git",
      "source": {
        "uri": "https://github.com/dpb587/bosh-release-compiler.git"
      }
    },
    {
      "name": "repo",
      "type": "git",
      "source": {
        "branch": "master",
        "private_key": "((git_private_key))",
        "uri": "git@github.com:dpb587/bosh-compiled-releases.git"
      }
    },
    {
      "name": "ubuntu-trusty",
      "type": "metalink-repository",
      "source": {
        "uri": "https://dpb587.github.io/upstream-blob-mirror/repository/bosh.io/stemcell/bosh-warden-boshlite-ubuntu-trusty-go_agent/index.xml"
      }
    },
    {
      "name": "github-dpb587-openvpn-bosh-release",
      "type": "git",
      "source": {
        "uri": "https://github.com/dpb587/openvpn-bosh-release.git"
      }
    },
    {
      "name": "bosh-io-cloudfoundry-bosh",
      "type": "bosh-io-release",
      "source": {
        "repository": "cloudfoundry/bosh"
      }
    },
    {
      "name": "bosh-io-concourse-concourse",
      "type": "bosh-io-release",
      "source": {
        "repository": "concourse/concourse"
      }
    },
    {
      "name": "bosh-io-cloudfoundry-garden-runc-release",
      "type": "bosh-io-release",
      "source": {
        "repository": "cloudfoundry/garden-runc-release"
      }
    },
    {
      "name": "bosh-io-cloudfoundry-uaa-release",
      "type": "bosh-io-release",
      "source": {
        "repository": "cloudfoundry/uaa-release"
      }
    },
    {
      "name": "bosh-io-cloudfoundry-community-docker-registry-boshrelease",
      "type": "bosh-io-release",
      "source": {
        "repository": "cloudfoundry-community/docker-registry-boshrelease"
      }
    },
    {
      "name": "bosh-io-cloudfoundry-syslog-release",
      "type": "bosh-io-release",
      "source": {
        "repository": "cloudfoundry/syslog-release"
      }
    },
    {
      "name": "bosh-io-cloudfoundry-dns-release",
      "type": "bosh-io-release",
      "source": {
        "repository": "cloudfoundry/dns-release"
      }
    }
  ],
  "resource_types": [
    {
      "name": "metalink-repository",
      "type": "docker-image",
      "source": {
        "repository": "dpb587/metalink-repository-resource"
      }
    }
  ]
}
